name: build

on:
  push:
  schedule:
    - cron: "10 3 * * *"

jobs:
  build:
    name: Build the site
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: |
          python -m pip install -r requirements.txt
          python fetch.py
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: api.ei.mikit.app
          enable_jekyll: true
